phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y tree
    finally:
      - echo This always runs even if the update or install command fails 
build:
    commands:
      - echo Build stage
      - echo Build on `date`
      - mvn compile
      - mvn package
      - mvn install
      - tree
